# Generated by Django 4.2.25 on 2025-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_alter_patient_options_patient_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_diagnosis',
            field=models.TextField(blank=True, help_text='Brief summary of current diagnosis or clinical notes.'),
        ),
    ]
